In [ ]:
import torch
torch.manual_seed(42)

In [89]:
class Model:
  def __init__(self, n_inputs, n_neurons):
    self.weight = torch.rand(n_inputs, n_neurons)
    self.bias = torch.rand(n_neurons)
    self.outputs = None
  def forward(self, inputs, activation = "Softmax"):
    cur = inputs @ self.weight + self.bias
    if activation == "Relu":
      self.outputs = self.relu(cur)
    elif activation == "Sigmoid":
      self.outputs = self.sigmoid(cur)
    else:
      self.outputs = self.softmax(cur)
    return self.outputs
  def normalize(self, inputs):
    return (inputs - torch.min(inputs)) / (torch.max(inputs) - torch.min(inputs))
  def relu(self, inputs):
    return torch.max(torch.tensor(0), inputs)
  def sigmoid(self, inputs):
    return 1 / (1 + torch.exp(-inputs))
  def softmax(self, inputs):
    return torch.exp(inputs) / torch.sum(torch.exp(inputs))
  def categoricalCrossEntropy(self, y_true, y_predicted):
      return torch.mean(-torch.sum(y_true * torch.log(y_predicted)))


In [90]:
input_data = torch.rand(10, 4)
input_data

tensor([[0.8073, 0.0229, 0.2565, 0.2147],
        [0.0752, 0.1878, 0.1430, 0.0822],
        [0.5730, 0.2669, 0.5206, 0.4199],
        [0.5344, 0.0458, 0.0899, 0.0479],
        [0.8480, 0.5166, 0.0744, 0.3076],
        [0.4948, 0.1691, 0.9045, 0.8588],
        [0.6202, 0.4139, 0.7908, 0.6309],
        [0.5426, 0.5617, 0.0648, 0.6416],
        [0.6826, 0.8085, 0.7371, 0.9256],
        [0.2342, 0.5410, 0.1318, 0.9293]])

In [91]:
input_data = torch.rand(10, 4)
input_layer = Model(4, 18)
hidden1 = Model(18, 18)
hidden2 = Model(18, 18)
hidden3 = Model(18, 18)
output = Model(18, 3)

input = input_layer.forward(input_data, activation = "Sigmoid")
hidden_1 = hidden1.forward(input, activation = "Sigmoid")
hidden_2 = hidden2.forward(hidden_1, activation = "Sigmoid")
hidden_3 = hidden3.forward(hidden_2, activation = "Sigmoid")
# lets normalize before we use softmax
output_ = output.forward(hidden3.normalize(hidden_3), activation="Softmax")

y_true = torch.randint(0, 2, (10, 3)).float()  # Binary classification for simplicity

# Calculate categorical cross-entropy loss
loss = output.categoricalCrossEntropy(y_true, output_)
print("Categorical Cross-Entropy Loss:")
print(loss.item())


print("The input layer is:\n", input_data)
print("The out put is: \n", output_)

Categorical Cross-Entropy Loss:
50.683746337890625
The input layer is:
 tensor([[0.4767, 0.0679, 0.8241, 0.5590],
        [0.3559, 0.9473, 0.2367, 0.2519],
        [0.3284, 0.5573, 0.1115, 0.6081],
        [0.0162, 0.2305, 0.2075, 0.1367],
        [0.6146, 0.7197, 0.3777, 0.3498],
        [0.5106, 0.0947, 0.0254, 0.1761],
        [0.1375, 0.5705, 0.9036, 0.8568],
        [0.1922, 0.7782, 0.9385, 0.3942],
        [0.3370, 0.0276, 0.4640, 0.3063],
        [0.6262, 0.0409, 0.4521, 0.5879]])
The out put is: 
 tensor([[0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378],
        [0.0145, 0.0478, 0.0378]])


In [92]:
input_data = torch.rand(10, 4)
input_layer = Model(4, 18)
hidden1 = Model(18, 18)
hidden2 = Model(18, 18)
hidden3 = Model(18, 18)
output = Model(18, 3)
input = input_layer.forward(input_data, activation = "Sigmoid")
hidden_1 = hidden1.forward(input, activation = "Sigmoid")
hidden_2 = hidden2.forward(hidden_1, activation = "Sigmoid")
hidden_3 = hidden3.forward(hidden_2, activation = "Sigmoid")
# lets normalize before we use softmax
output_ = output.forward(hidden3.normalize(hidden_3), activation="Softmax")

y_true = torch.randint(0, 2, (10, 3)).float()  # Binary classification for simplicity

# Calculate categorical cross-entropy loss
loss = output.categoricalCrossEntropy(y_true, output_)
print("Categorical Cross-Entropy Loss:")
print(loss.item())


print("The input layer is:\n", input_data)
print("The out put is: \n", output_)


Categorical Cross-Entropy Loss:
64.38774108886719
The input layer is:
 tensor([[0.6320, 0.4540, 0.5789, 0.2766],
        [0.2107, 0.0935, 0.5407, 0.0408],
        [0.0362, 0.9475, 0.7096, 0.4179],
        [0.2673, 0.9424, 0.4784, 0.0833],
        [0.8569, 0.9653, 0.5912, 0.8596],
        [0.0992, 0.5138, 0.9902, 0.0082],
        [0.0265, 0.5443, 0.6335, 0.6256],
        [0.3571, 0.9175, 0.8619, 0.0061],
        [0.0248, 0.9241, 0.2965, 0.5958],
        [0.6766, 0.6150, 0.2421, 0.1592]])
The out put is: 
 tensor([[0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282],
        [0.0132, 0.0586, 0.0282]])
